### ISSUE TITLE
role_meta_info中wiki信息过长

### ISSUE THREAD

**Issue by cppww** [OFA-Sys/Ditto#6]
您好，我有如下的一个问题：
role_meta_info中一个角色的wiki信息内容很长，在拼接角色A和角色B相关内容prompt用于Query Simulation时，sequence_length远超部分Qwen模型的max_length，请问你们在做非Qwen-72B的DITTO时是如何处理这个情况，让模型可以得到Query和Response Simulation的回复的呀？

**Comment by Lukeming-tsinghua** [comment]
感谢提问！考虑 sequence_length 是 8192 的情况下，我们在拼接 prompt 时首先会先计算[不包含wiki]的 prompt 的长度，并预留 2048 的 max_new_tokens 空间用于生成 query 和 response。例如，在不包含 wiki 时 prompt 长度是 1024，则留给 wiki 的空间是 8192-2048-1024=5120。确定 wiki 的最大长度后我们会截取 wiki 的前 5120 个 token 作为 context。
