### ISSUE TITLE
麻烦数据提供下，gitlfs没法下载，感谢

### ISSUE THREAD

**Issue by lin1490188** [OFA-Sys/Ditto#7]
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. Failed to fetch some objects from 'https://github.com/OFA-Sys/Ditto.git/info/lfs'

**Comment by protossw512** [comment]
Hi @Lukeming-tsinghua Would you like to take a temporary solution of zipping all the data and putting it to the google drive?

**Comment by Lukeming-tsinghua** [comment]
Thanks for your kind remind. Please kindly download data from this shared link http://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/lukeming.lkm/public/ditto_data.zip

**Comment by KundaYang** [comment]
Link seems down?

**Comment by KundaYang** [comment]
> Link seems down?

Sorry, seems that it's Chrome's problem, Safari works fine.
